name: App Deploy tester

on:
  workflow_dispatch:  # manual trigger

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: "echo test"
      - name: Use Node.js ${{ env.NODE_VERSION }}
        run: "echo test"
      - name: npm install, build, and test
        run: "echo test"
      - name: Upload a Build Artifact
        run: "echo test"
    
  deployTest:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download a Build Artifact
        run: "echo test"
      
      - name: Azure Login
        run: "echo test"
    
      - name: 'Deploy to Azure WebApp'
        run: "echo test"
        
  testUi:
    name: Run UI tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download a Build Artifact
        run: "echo test"

      - name: Run UI Tests
        run: "echo test"
        
  approval:
    name: Approve PROD
    runs-on: ubuntu-latest
    needs: deployTest

    steps:
      - name: Download a Build Artifact
        run: "echo test"

      - name: Run UI Tests
        run: "echo test"

  deployProd:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    needs: approval

    steps:
      - name: Download a Build Artifact
        run: "echo test"

      - name: Run UI Tests
        run: "echo test"
