name: App Deploy tester

on:
  release:
    types: [created]
    
  workflow_dispatch:  # manual trigger

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          yarn
          yarn build
          yarn test
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: site          
          path: build          
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: site
          path: ${{ github.workspace }}/site
      
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: storm-actions-tester
          package: ${{ github.workspace }}/site
