# This is a basic workflow to help you get started with Actions

name: Sarjassa vai rinnan

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  vaihe1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Vaihe 1"
      
  vaihe2:  
    runs-on: ubuntu-latest
    needs: vaihe1
    steps:
      - run: echo "Vaihe 2"
  
  vaihe3:  
    runs-on: ubuntu-latest
    needs: vaihe1
    steps:
      - run: echo "Vaihe 3"
      
  vaihe4:  
    runs-on: ubuntu-latest
    needs: [vaihe2, vaihe3]
    steps:
      - run: echo "Vaihe 4"
